# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ClassfitteriOS' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ClassfitteriOS
    pod 'Firebase/Core'
    pod 'Firebase/Crash'
    pod 'Firebase/Auth'

  target 'ClassfitteriOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Firebase/Core'
    pod 'Firebase/Crash'
    pod 'Firebase/Auth'
  end

  target 'ClassfitteriOSUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Firebase/Core'
    pod 'Firebase/Crash'
    pod 'Firebase/Auth'
  end

end
