# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'ClassfitteriOS' do
  source 'https://github.com/CocoaPods/Specs.git'
  use_frameworks!
  
  pod 'Firebase/Core', :inhibit_warnings => true
  pod 'Firebase/Crash', :inhibit_warnings => true
  pod 'Firebase/Auth', :inhibit_warnings => true
  pod 'Firebase/Database', :inhibit_warnings => true
  pod 'RxSwift',    '~> 3.0.0.alpha.1', :inhibit_warnings => true
  pod 'RxCocoa',    '~> 3.0.0.alpha.1', :inhibit_warnings => true
  pod 'PromiseKit', :git => 'https://github.com/mxcl/PromiseKit.git', :branch => 'swift-3.0', :inhibit_warnings => true
  pod 'Swinject', :git => 'https://github.com/Swinject/Swinject.git', :branch => 'master', :inhibit_warnings => true
  pod 'Firebase/Messaging'
  

  target 'ClassfitteriOSTests' do
    inherit! :search_paths
    pod 'Firebase/Core', :inhibit_warnings => true
    pod 'Firebase/Crash', :inhibit_warnings => true
    pod 'Firebase/Auth', :inhibit_warnings => true
    pod 'RxSwift',    '~> 3.0.0.alpha.1', :inhibit_warnings => true
    pod 'RxCocoa',    '~> 3.0.0.alpha.1', :inhibit_warnings => true
    pod 'PromiseKit', :git => 'https://github.com/mxcl/PromiseKit.git', :branch => 'swift-3.0', :inhibit_warnings => true
  end

  target 'ClassfitteriOSUITests' do
    inherit! :search_paths
    pod 'Firebase/Core', :inhibit_warnings => true
    pod 'Firebase/Crash', :inhibit_warnings => true
    pod 'Firebase/Auth', :inhibit_warnings => true
    pod 'RxSwift',    '~> 3.0.0.alpha.1', :inhibit_warnings => true
    pod 'RxCocoa',    '~> 3.0.0.alpha.1', :inhibit_warnings => true
    pod 'PromiseKit', :git => 'https://github.com/mxcl/PromiseKit.git', :branch => 'swift-3.0', :inhibit_warnings => true
  end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
            config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.10'
        end
    end
end

end
