# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '8.0'


pod 'RxSwift', :git => 'https://github.com/ReactiveX/RxSwift.git', :branch => 'master', :inhibit_warnings => true
pod "PromiseKit", "~> 4.0", :inhibit_warnings => true
pod 'Swinject', :inhibit_warnings => true



target 'ClassfitteriOS' do

  pod 'Firebase/Core', :inhibit_warnings => true
  pod 'Firebase/Crash', :inhibit_warnings => true
  pod 'Firebase/Auth', :inhibit_warnings => true
  pod 'Firebase/Database', :inhibit_warnings => true
  pod 'Firebase/Messaging', :inhibit_warnings => true 
  

  target 'ClassfitteriOSTests' do
    inherit! :search_paths
    pod 'Firebase/Core', :inhibit_warnings => true
  pod 'Firebase/Crash', :inhibit_warnings => true
  pod 'Firebase/Auth', :inhibit_warnings => true
  pod 'Firebase/Database', :inhibit_warnings => true
  pod 'Firebase/Messaging', :inhibit_warnings => true 
  end

  target 'ClassfitteriOSUITests' do
    inherit! :search_paths
    pod 'Firebase/Core', :inhibit_warnings => true
  pod 'Firebase/Crash', :inhibit_warnings => true
  pod 'Firebase/Auth', :inhibit_warnings => true
  pod 'Firebase/Database', :inhibit_warnings => true
  pod 'Firebase/Messaging', :inhibit_warnings => true 
     end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
            config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.10'
        end
    end
end

end
